namespace ContactBook;

public class ContactBook
{
    public const string NEXT_PAGE = "+";
    public const string PREV_PAGE = "-";
    public const string GOTO_PAGE = "G";
    public const string PAGE_SIZE = "S";
    public const string CREATE_CONTACT = "C";
    public const string REVIEW_CONTACT = "R";
    public const string UPDATE_CONTACT = "U";
    public const string DELETE_CONTACT = "D";
    public const string FIND_CONTACTs = "F";
    public const string ORDER_CONTACTS = "O";
    public const string DEDUPLICATE_CONTACTS = "M";
    public const string EXIT = "X";

        public readonly string[] COMMANDS = new string[]
        {
    NEXT_PAGE, PREV_PAGE,  GOTO_PAGE,   PAGE_SIZE, CREATE_CONTACT,
    REVIEW_CONTACT, UPDATE_CONTACT,  DELETE_CONTACT, FIND_CONTACTs,
    ORDER_CONTACTS,   DEDUPLICATE_CONTACTS,  EXIT
        };

        private List<Contact> allContacts;
        public ContactBook(List<Contact> contacts = null!)
    {
        allContacts = (contacts == null) ? new List<Contact>() : contacts;
    }

    public void Start()
    {
        ShowWelcomeScreen();

        string input;
        do
        {
            ShowContacts();

            do
        {
            ShowInputootions();
            input = GetInput();
        }
        while(!IsValidInput(input));

        ProcessInput(input);
        }
        while(!ConfirmExit());

        ShowExitScreen();
    }

    private void ShowWelcomeScreen()
    {
     Console.WriteLine("Welcome to Eliud's Contact Book!");
     PressEnterToContinue();
    }
    
    private void ShowContacts()
    {
        Console.Clear();

if(allContacts.Count <= 0)
        {
            Console.WriteLine("No contacts found.");
        }
        else
        {
            int indexCol = -Math.Max("#".Length, allContacts.Count.ToString().Length);
            int fnameCol = -Math.Max("First Name".Length, allContacts.Max(c => c.GetFName()?.Length ?? 0));
            int lnameCol = -Math.Max("Last Name".Length, allContacts.Max(c => c.GetLname()?.Length ?? 0));
            int phoneCol = -Math.Max("Phone".Length, allContacts.Max(c => c.GetPhone()?.Length ?? 0));
            int emailCol = -Math.Max("Email".Length, allContacts.Max(c => c.GetEmail()?.Length ?? 0));

           Console.WriteLine(""
           + "{0, " + indexCol + "}  "
           + "{1, " + fnameCol + "}  "
           + "{2, " + lnameCol + "}  " 
           + "{3, " + phoneCol + "}  "
           + "{4, " + emailCol + "}  ",
           "#", "First Name", "Last Name", "Phone", "Email");
           Console.WriteLine(new string('─', 80));

            for(int i = 0; i < allContacts.Count; i++)
            {
                Contact c = allContacts[i];

                Console.WriteLine(""
               + "{0, " + indexCol + "}  "
               + "{1, " + fnameCol + "}  "
               + "{2, " + lnameCol + "}  "
               + "{3, " + phoneCol + "}  "
               + "{4, " + emailCol + "}  ",
               i, c.GetFName(), c.GetLname(), c.GetPhone(), c.GetEmail());
            }
        }
    }

    private void ShowInputootions()
    {;
    }

    private string GetInput()
    {
      return "";
    }

    private bool IsValidInput(string input)
    {
       return true;
    }

    private void ProcessInput(string input)
    {
    
    }

    private bool ConfirmExit()
    {
      return true;
    }

    private void ShowExitScreen()
    {
   
    }

    private void PressEnterToContinue()
    {
        Console.Write("Press Enter to continue...");
        while(Console.ReadKey(true).Key != ConsoleKey.Enter);
    }
}

